spring:
  datasource:
    url: jdbc:mysql://rm-bp149r27afbr5709j.mysql.rds.aliyuncs.com:3306/hospital?characterEncoding=UTF-8
    username: hospital_user
    password: wwz2020#@!
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#logging:
#  level:
#    com.example.demo.dao: info
